source 'https://rubygems.org'
gem 'cucumber'
gem 'rspec'
# gem 'watir-webdriver'
# gem 'watir'
# gem 'selenium-webdriver'
gem 'json'
# gem 'addressable', '~> 2.0'
# gem 'net/http'
# gem 'logger'
gem 'require_all'
gem 'page-object'
gem 'childprocess'
gem 'i18n' ,'1.5.1'
gem 'faker', '1.9.1'
gem 'rubyzip', '1.3.0'
gem 'selenium-webdriver', '3.4.1'
gem 'watir', '6.10.3'
# gem 'public_suffix', '3.1.1'